//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBinding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunId { get; set; }
        public int kategoriId { get; set; }
        public string Ad { get; set; }
        public decimal fiyat { get; set; }
        public Nullable<int> stok { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
