//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLINQExercises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public Siparis()
        {
            this.SiparisUrun = new HashSet<SiparisUrun>();
        }
    
        public int SiparisId { get; set; }
        public int UyeId { get; set; }
        public int SiparisDurumTip { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual ICollection<SiparisUrun> SiparisUrun { get; set; }
    }
}
