//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLINQExercises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public Urun()
        {
            this.Sepet = new HashSet<Sepet>();
            this.SiparisUrun = new HashSet<SiparisUrun>();
        }
    
        public int UrunId { get; set; }
        public int kategoriId { get; set; }
        public string Ad { get; set; }
        public decimal fiyat { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual ICollection<Sepet> Sepet { get; set; }
        public virtual ICollection<SiparisUrun> SiparisUrun { get; set; }
    }
}
