#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDataSource
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AspNetOrnek")]
	public partial class OrnekClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIsIlani(IsIlani instance);
    partial void UpdateIsIlani(IsIlani instance);
    partial void DeleteIsIlani(IsIlani instance);
    #endregion
		
		public OrnekClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AspNetOrnekConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrnekClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrnekClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrnekClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrnekClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IsIlani> IsIlanis
		{
			get
			{
				return this.GetTable<IsIlani>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IsIlani")]
	public partial class IsIlani : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IsIlaniId;
		
		private string _Baslik;
		
		private string _Icerik;
		
		private System.DateTime _YyinlamaTarihi;
		
		private System.DateTime _BitisTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIsIlaniIdChanging(int value);
    partial void OnIsIlaniIdChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnYyinlamaTarihiChanging(System.DateTime value);
    partial void OnYyinlamaTarihiChanged();
    partial void OnBitisTarihiChanging(System.DateTime value);
    partial void OnBitisTarihiChanged();
    #endregion
		
		public IsIlani()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsIlaniId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IsIlaniId
		{
			get
			{
				return this._IsIlaniId;
			}
			set
			{
				if ((this._IsIlaniId != value))
				{
					this.OnIsIlaniIdChanging(value);
					this.SendPropertyChanging();
					this._IsIlaniId = value;
					this.SendPropertyChanged("IsIlaniId");
					this.OnIsIlaniIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YyinlamaTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime YyinlamaTarihi
		{
			get
			{
				return this._YyinlamaTarihi;
			}
			set
			{
				if ((this._YyinlamaTarihi != value))
				{
					this.OnYyinlamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._YyinlamaTarihi = value;
					this.SendPropertyChanged("YyinlamaTarihi");
					this.OnYyinlamaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime BitisTarihi
		{
			get
			{
				return this._BitisTarihi;
			}
			set
			{
				if ((this._BitisTarihi != value))
				{
					this.OnBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._BitisTarihi = value;
					this.SendPropertyChanged("BitisTarihi");
					this.OnBitisTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
