//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsIlani
    {
        public int IsIlaniId { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public System.DateTime YayinlanmaTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public string YayindaMi { get; set; }
        public string FirmaResim { get; set; }
        public string FirmaAdi { get; set; }
    }
}
